# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
import numpy as np

def create_rand_matrix(num_rows, num_cols):
    matrix_shape = (num_rows, num_cols)
    rand_matrix = np.zeros(matrix_shape)
    for i in range(num_rows):
        for j in range(num_cols):
            rand_matrix[i][j] = np.random.randint(1, 11)
    return rand_matrix

In [4]:
A = create_rand_matrix(4, 4)
B = create_rand_matrix(4, 4)
C = create_rand_matrix(4, 4)
print(A, '\n\n', B, '\n\n', C)

[[2. 7. 6. 7.]
 [4. 5. 3. 6.]
 [7. 8. 8. 1.]
 [4. 6. 1. 4.]] 

 [[ 4.  2.  7.  3.]
 [ 9.  1.  9. 10.]
 [ 4.  1.  4.  6.]
 [ 2.  3.  1.  4.]] 

 [[1. 1. 1. 3.]
 [5. 9. 6. 6.]
 [5. 9. 1. 8.]
 [7. 5. 8. 4.]]


In [12]:
left_hand_side = A.dot(B + C)
right_hand_side = (A.dot(B) + A.dot(C))
print(left_hand_side, '\n')
print(right_hand_side, ''\n')
print(left_hand_side == right_hand_side)

SyntaxError: unexpected character after line continuation character (<ipython-input-12-ef754a70406e>, line 4)

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [11]:
left_hand_side = B*C
left_hand_side = A*left_hand_side
right_hand_side = A*B
right_hand_side = right_hand_side * C

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [3]:
# Your code here 

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [4]:
# Your code here 

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [5]:
# Your code here 

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 