# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
import numpy as np

def create_rand_matrix(num_rows, num_cols):
    matrix_shape = (num_rows, num_cols)
    rand_matrix = np.zeros(matrix_shape)
    for i in range(num_rows):
        for j in range(num_cols):
            rand_matrix[i][j] = np.random.randint(1, 11)
    return rand_matrix

In [4]:
A = create_rand_matrix(4, 4)
B = create_rand_matrix(4, 4)
C = create_rand_matrix(4, 4)
print(A, '\n\n', B, '\n\n', C)

[[2. 7. 6. 7.]
 [4. 5. 3. 6.]
 [7. 8. 8. 1.]
 [4. 6. 1. 4.]] 

 [[ 4.  2.  7.  3.]
 [ 9.  1.  9. 10.]
 [ 4.  1.  4.  6.]
 [ 2.  3.  1.  4.]] 

 [[1. 1. 1. 3.]
 [5. 9. 6. 6.]
 [5. 9. 1. 8.]
 [7. 5. 8. 4.]]


In [13]:
left_hand_side = A.dot(B + C)
right_hand_side = (A.dot(B) + A.dot(C))
print(left_hand_side, '\n')
print(right_hand_side, '\n')
print(left_hand_side == right_hand_side)

[[225. 192. 214. 264.]
 [171. 140. 176. 194.]
 [228. 189. 225. 290.]
 [149. 114. 163. 166.]] 

[[225. 192. 214. 264.]
 [171. 140. 176. 194.]
 [228. 189. 225. 290.]
 [149. 114. 163. 166.]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [16]:
left_hand_side = B.dot(C)
left_hand_side = A.dot(left_hand_side)
right_hand_side = A.dot(B)
right_hand_side = right_hand_side.dot(C)
print(left_hand_side, '\n')
print(right_hand_side, '\n')
print(left_hand_side == right_hand_side)

[[1819. 2123. 1565. 1979.]
 [1438. 1730. 1212. 1603.]
 [2140. 2582. 1710. 2444.]
 [1325. 1605. 1086. 1504.]] 

[[1819. 2123. 1565. 1979.]
 [1438. 1730. 1212. 1603.]
 [2140. 2582. 1710. 2444.]
 [1325. 1605. 1086. 1504.]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [17]:
left_hand_side = A.dot(B)
right_hand_side = B.dot(A)

print(left_hand_side, '\n')
print(right_hand_side, '\n')
print(left_hand_side == right_hand_side)

[[109.  38. 108. 140.]
 [ 85.  34.  91. 104.]
 [134.  33. 154. 153.]
 [ 82.  27.  90.  94.]] 

[[ 77. 112.  89.  59.]
 [125. 200. 139. 118.]
 [ 64. 101.  65.  62.]
 [ 39.  61.  33.  49.]] 

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [25]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([6, 2, 5, 2, 5, 2, 1])
print(x)
print(y)
print(x.dot(y))
print(y.dot(x))

[1 2 3 4 5 6 7]
[6 2 5 2 5 2 1]
77
77


## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [26]:
left_hand_side = A.dot(B)
left_hand_side = left_hand_side.transpose()
print(left_hand_side)

print(left_hand_side, '\n')
print(right_hand_side, '\n')
print(left_hand_side == right_hand_side)

[[2. 7. 6. 7.]
 [4. 5. 3. 6.]
 [7. 8. 8. 1.]
 [4. 6. 1. 4.]]
[[ 4.  2.  7.  3.]
 [ 9.  1.  9. 10.]
 [ 4.  1.  4.  6.]
 [ 2.  3.  1.  4.]]
[[109.  38. 108. 140.]
 [ 85.  34.  91. 104.]
 [134.  33. 154. 153.]
 [ 82.  27.  90.  94.]] 

[[ 77. 112.  89.  59.]
 [125. 200. 139. 118.]
 [ 64. 101.  65.  62.]
 [ 39.  61.  33.  49.]] 

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 